MY_DW_DEV = ["mdw-dev-my1",3306,"mdw","mdw_admin","mdw_admin","mdw 개발"]
MY_DW_QA= ["mdw-qa-my1",3306,"mdw","mdw_admin","mdw_admin","mdw QA"]
MY_DW_PROD = ["mdw-prod-my1",3306,"mdw","mdw","mdw_admin","mdw 운영1"]
MY_DW_PROD2 = ["mdw-prod-my2",3306,"mdw","mdw","mdw_admin","mdw 운영2"]
MY_DW_PROD3 = ["mdw-prod-my3",3306,"mdw","mdw","mdw_admin","mdw 운영3"]
